services:
  db:
    build:
      context: .
      dockerfile: mysql.dockerfile
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  db2:
    build:
      context: .
      dockerfile: mysql.dockerfile      
    container_name: mysql-container2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

webapp:
    build:
      context: .
      dockerfile: app/app.dockerfile
    container_name: go-webapp
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql-container
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_NAME: testdb

webapp2:
    build:
      context: .
      dockerfile: app/app.dockerfile
    container_name: go-webapp2
    depends_on:
      - db2
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql-container2
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_NAME: testdb

volumes:
  db_data:

