name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the self-hosted CentOS runner (or remove if using GitHub-hosted runners)

    steps:
      # 1. Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: taniya-github/zebra  # Your GitHub repository name
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH key for accessing the repo

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build and run Docker containers using Docker Compose
      - name: Build and run Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d --build

      # 4. Deploy to CentOS VM (Target)
      - name: Deploy to CentOS VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} admin@localhost << EOF
            # Setup deployment directory
            mkdir -p /home/admin/cicd_target
            cd /home/admin/cicd_target

            # Clone the repository and deploy the application
            git clone git@github.com:taniya-github/zebra.git .
            docker-compose -f docker-compose.yml up -d --build
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

